name: Deploy Jekyll with GitHub Pages dependencies preinstalled

on:
  push:
    branches:
      - main

  workflow_dispatch:  # Allows you to trigger the workflow manually from the Actions tab

permissions:
  contents: read  # Allow read access to repository contents
  pages: write  # Allow writing to GitHub Pages
  id-token: write  # Allow requesting an ID token to interact with other services

concurrency:
  group: "pages"
  cancel-in-progress: false  # Do not cancel in-progress deployments

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'  # Specify the Ruby version for the Jekyll build

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install  # This installs Jekyll and any other dependencies in your Gemfile

      - name: Build with Jekyll
        run: |
          bundle exec jekyll build --source ./ --destination ./_site  # Build the Jekyll site

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./_site  # Upload the site files as an artifact

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}  # URL of the deployed site
    runs-on: ubuntu-latest
    needs: build  # Ensure this job runs after the build job
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4  # Action to deploy to GitHub Pages
